### PR TITLE
ENH: Compatibility with docutils>=0.18 (from support with sphinx>=5)

### PR DESCRIPTION
**Pull request by AakashGfude**
This PR updates sphinx-exercise to support `sphinx5` and by proxy `docutils>=0.18.<0.19`

fixes https://github.com/executablebooks/sphinx-exercise/issues/59

### CODE REVIEW

**Comment by mmcky** [comment]
Let's update the requirements so we test against `sphinx4` and `sphinx5`

**Comment by mmcky** [comment]
@AakashGfude I don't think we need to work on supporting `python=3.7` as it is not receiving security updates in ~3 months and will be deprecated anyway.

**Comment by mmcky** [comment]
@AakashGfude can you do a final review and let me know if you think we need any further testing before putting together a new release

**Comment by AakashGfude** [comment]
@mmcky this looks good to me. I think we can go ahead and merge.

**Comment by AakashGfude** [comment]
@mmcky I think we still need some testing for sphinx5. give me a few moments,

**Comment by AakashGfude** [comment]
Looks good to me now @mmcky , should we cut a release?

**Pull request merged**
