### PR TITLE
👌  IMPROVE: Bug fix, latex support and some refactoring

### PR DESCRIPTION
**Pull request by AakashGfude**
- [x] fixes https://github.com/executablebooks/sphinx-exercise/issues/32
- [x] latex support. fixes https://github.com/executablebooks/sphinx-exercise/issues/30
- [x] refactoring and removing redundant code

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @AakashGfude let me know when you're done with this `refactor` etc. Then I can dive in and continue work on the `gated` directive idea to support code execution to propose to the `EBP` community.

**Comment by AakashGfude** [comment]
@mmcky This should be ready to go.

**Review by mmcky — COMMENTED** [review]
@AakashGfude just going through these changes. I see a lot of changes to object names to make them `less` general. I think this makes the code a lot more readable 👍 but is there any tradeoff here. Are these objects becoming less general and code becoming more duplicated or is there very little overlap.

**Comment by AakashGfude** [comment]
> @AakashGfude just going through these changes. I see a lot of changes to object names to make them `less` general. I think this makes the code a lot more readable 👍 but is there any tradeoff here?
> 
> Are these objects becoming less general and code becoming more duplicated or is there very little overlap.

An approach of less general was done, to prevent overwriting/interference from other extensions. For example, node names like `enumerable_node`, `unenumerable_node` were getting affected by other extensions. Have tried to reduce duplicity. Let me know if there's any particular instance that is catching your attention.

**Review by mmcky — APPROVED** [review]

**Comment by mmcky** [comment]
> > @AakashGfude just going through these changes. I see a lot of changes to object names to make them `less` general. I think this makes the code a lot more readable 👍 but is there any tradeoff here?
> > Are these objects becoming less general and code becoming more duplicated or is there very little overlap.
> 
> An approach of less general was done, to prevent overwriting/interference from other extensions. For example, node names like `enumerable_node`, `unenumerable_node` were getting affected by other extensions. Have tried to reduce duplicity. Let me know if there's any particular instance that is catching your attention.

thanks @AakashGfude mainly curious. They aren't large methods so looks good to me. After adding the documentation / comments -- please feel free to merge.

**Comment by AakashGfude** [comment]
> thanks @AakashGfude mainly curious. They aren't large methods so looks good to me. After adding the documentation / comments -- please feel free to merge.

I will just merge this one now? So that you can experiment with that prototype. Will reiterate tomorrow, to add comments and any other improvements.

**Pull request merged**
